#!/bin/bash
echo "installing mattjmorrison's custom dotfiles"

DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

symlink_file_in_home () {
    FILE=$1
    mkdir -p $(dirname "$HOME/$FILE")
    if [[ -f "$HOME/$FILE" && ! -L "$HOME/$FILE" ]]; then
        NOW=`date +"%F-%T"`
        RENAMED_FILE="${HOME}/${FILE}.${NOW}"
        echo "${HOME}/${FILE} exists - renaming to ${RENAMED_FILE}"
        mv "${HOME}/${FILE}" "${RENAMED_FILE}"
    fi
    ln -sf "${DIR}/${FILE}" "${HOME}/${FILE}"
}

symlink_file_in_home ".config/karabiner/karabiner.json"
